import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { getLocale } from "next-intl/server"
import { Geist, Geist_Mono, Geologica } from "next/font/google"
import React, { Suspense } from "react"
import Providers from "./_providers"
import "./globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

const geologica = Geologica({
    variable: "--font-geologica",
    subsets: ["cyrillic", "latin"],
})

export const metadata: Metadata = {
    title: "FunWay",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const locale = await getLocale()

    return (
        <html lang={locale}>
            <body
                className={`${geologica.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-[#F5FAFF]`}
            >
                <Suspense>
                    <Providers>
                        {children}
                        <Toaster />
                    </Providers>
                </Suspense>
            </body>
        </html>
    )
}
