import type { Metadata } from "next";
import { Geist, Geist_Mono, Geologica } from "next/font/google";
import { getLocale } from "next-intl/server";
import type React from "react";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./_providers";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const geologica = Geologica({
	variable: "--font-geologica",
	subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
	title: "Ruzimurod",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale}>
			<body
				className={`${geologica.variable} ${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-[#F5FAFF]`}
			>
				<Suspense>
					<Providers>
						<NextTopLoader
							color="#0019ff"
							initialPosition={0.08}
							crawlSpeed={200}
							height={4}
							showSpinner={false}
						/>
						{children}
						<Toaster />
					</Providers>
				</Suspense>
			</body>
		</html>
	);
}
